### ISSUE TITLE
unprotected ascon having incorrect tag and ct

### ISSUE THREAD

**Issue by zliu1Charlotte** [aneeshkandi14/ascon-hw-public#1]
Hi, could you please share a test vector you did with the unprotected ascon? 
I tried your unprotected ascon but the tag and ct are incorrect. 
Thanks.

**Comment by anubhab001** [comment]
Hello @zliu1Charlotte, 
Thank you for your interest in our research. We are working on test cases. Please stay tuned. ✌️

**Comment by aneeshkandi14** [comment]
> Hi, could you please share a test vector you did with the unprotected ascon? I tried your unprotected ascon but the tag and ct are incorrect. Thanks.

Hello @zliu1Charlotte,
Please find some testcases in `testbench/testcases.txt`. Do let us know if you are facing any issues.
Thank you.
